var arrLang = {
    'ENG': {
        'home': 'Home',
        'language': 'Language',
        'conditions': 'Conditions for passing the course',
        'result': 'Learning outcomes of the course unit',
        'point0': 'Two written tests are planned during the semester, each for 20 points.',
        'point1': 'Student must obtain at least 20 points of 40 during the semester to attend the final examination and get credits.',
        'point2': 'The aim is to acquire the basics of modelling, simulation, analysis and synthesis of systems, which are based on discrete changes in conditions caused by events.',
        'point3': 'It is to become familiar with the basics of the analysis and synthesis algorithms for a particular modeling formalism, especially Petri nets and show their use in the analysis and synthesis systems in various application areas.',
        'point4': 'Basic properties of event systems, reachability, boundedness, liveness and deadlocks.',
        'point5': 'Sequential description of the behavior of Petri nets.',
        'point6': 'Structural analysis and invariants of Petri nets.',
        'point7': 'Liveness analysis in Petri nets. Boundedness analysis in Petri nets.',
        'point8': 'Analysis of deadlocks in Petri nets.',
        'point9': 'Reachability analysis in state machines and Petri nets.',
        'point10': 'Synthesis of models from regular expressions and machines based on Petri nets.',
        'point11': 'Nonsequential description of the behavior of event systems.',
        'point12': 'Verification of reachability by nonsequential processes.',
        'point13': 'Algorithms for verifying the feasibility of sequential and nonsequential scenarios.',
        'point14': 'Synthesis of models based on Petri nets from nonsequential scenarios.',
        'point15': 'Examples of the use of analysis and synthesis in the application areas of business processes, flexible manufacturing systems and communication protocols.',
        'course content and reading': 'Course contents and Recomended Reading',
        'materials': 'Study Materials'
    },
    'SVK': {
        'home': 'Domov',
        'language': 'Jazyk',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'result': 'Výsledky vzdelávania',
        'point0': 'Dve zápočtové písomky, každá po 20 bodov. Nutnou podmienkou udelenia kreditov je získanie najmenej polovice maximálneho počtu bodov.',
        'point1':'Cieľom predmetu je osvojiť si základy modelovania, simulácie, analýzy a syntézy systémov, ktorých základnou charakteristikou sú diskrétne zmeny stavov vyvolané udalosťami.',
        'point2':'Ďalej je cieľom oboznámiť sa so základnými algoritmami analýzy a syntézy pre konkrétne modelovacie formalizmy, najmä Petriho siete a ukázať ich použitie pri analýze a syntéze systémov v rôznych aplikačných oblastiach.',        
        'point3': 'Na skúške študent môže získať maximálne 60 bodov. Nutnou podmienkou absolvovania predmetu je získanie celkovo najmenej 56 bodov.',
        'point4': 'Základné vlastnosti udalostných systémov, dosiahnuteľnosť, ohraničenoť, živosť a deadlocky.',
        'point5': 'Sekvenčný popis správania v Petriho sieťach.',
        'point6': 'Štrukturálna analýza a invarianty Petriho sietí.',
        'point7': 'Analýza živosti v Petriho sieťach. Analýza ohraničenosti v Petriho sieťach.',
        'point8': 'Analýza deadlockov v Petriho sieťach.',
        'point9': 'Analýza dosiahnuteľnosti v automatoch a v Petriho sieťach.',
        'point10': 'Syntéza modelov založených na Petriho sieťach z regulárnych výrazov a automatov.',
        'point11': 'Nesekvenčné popisy správania udalostných systémov.',
        'point12': 'Overovanie dosiahnuteľnosti pomocou nesekvenčných procesov.',
        'point13': 'Algoritmy overovania uskutočniteľnosti sekvenčných a nesekvenčných scenárov.',
        'point14': 'Syntéza modelov založených na Petriho sieťach z nesekvenčných scenárov.',
        'point15': 'Príklady použitia analýzy a syntézy v aplikačných oblastiach podnikových procesov, pružných výrobných systémov a komunikačných protokolov.',
        'course content and reading': 'Stručná osnova a Literatúra',
        'materials': 'Študijné Materiály'
    }
};