var arrLang = {
    'ENG': {
        'home': 'Home',
        'language': 'Language',
        'conditions': 'Conditions for passing the course',
        'result': 'Learning outcomes of the course unit',
        'point0': 'During the semester - 30 points (30 credit tests)The necessary credit - 15 pointsAfter the end of the semester - exam (70 points)Result: The sum of the points of the semester tests, specified tasks and exams.A final assessment by the study of procedure STU.',
        'point1': 'Student must obtain at least 20 points of 40 during the semester to attend the final examination and get credits.',
        'point2': 'The aim is to acquire the basics of modelling, simulation, analysis and synthesis of systems, which are based on discrete changes in conditions caused by events.',
        'point3': 'It is to become familiar with the basics of the analysis and synthesis algorithms for a particular modeling formalism, especially Petri nets and show their use in the analysis and synthesis systems in various application areas.',
        'point4': 'Basic properties of event systems, reachability, boundedness, liveness and deadlocks.',
        'point5': 'Limits Theorems.',
        'point6': 'Random vector.',
        'point7': 'Independence of random variables, joint distribution, covariance and correlation matrix.',
        'point8': 'Descriptive statistics.',
        'point9': 'Random choice and estimation of mean and variance.',
        'point10': 'Confidence intervals.',
        'point11': 'A statistical hypothesis test.',
        'point12': 'Some parametric and nonparametric tests, good-fit tests.',
        'course content and reading': 'Course contents and Recomended Reading',
        'materials': 'Study Materials'
    },
    'SVK': {
        'home': 'Domov',
        'language': 'Jazyk',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'result': 'Výsledky vzdelávania',
        'point0': 'Počas semestra bude zápočet za 30 bodov. Na na skúšku je potrebných 15 bodov. Body získané počas semestra sa započítavajú do celkového hodnotenia.',
        'point1':'Po skončení semestra bude písomná skúška za 70 bodov. Súčet bodov zo semestra a skúšky určuje hodnotenie podľa čl.16 študijného poriadku STU.',
        'point2':'Absolvovaním predmetu študent by mal rozumieť základným metódam štatistickej analýzy dát a byť schopný ich aplikovať na reálnych dátových súboroch.',        
        'point3': 'Náhodné udalosti, pravdepodobnostné miery, podmienená pravdepodobnosť.',
        'point4': 'Náhodná premenná.',
        'point5': 'Rozdelenie pravdepodobnosti náhodnej premennej.',
        'point6': 'Základné charakteristiky náhodných premenných (momenty náhodných premenných).',
        'point7': 'Typy pravdepodobnostných rozdelení (rovnomerné, binomické, hypergeometrické, Poissonovo, rovnomerné spojité, normálne, exponenciálne).',
        'point8': 'Limitné vety.',
        'point9': 'Náhodný vektor',
        'point10': 'Nezávislosť náhodných premenných, združené rozdelenie pravdepodobnosti, kovariančná a korelačná matica a ich základné vlastnosti.',
        'point11': 'Popisná štatistika, intervalové a bodové odhady.',
        'point12': 'Testovania štatistických hypotéz: parametrické a neparametrické testy a testy dobrej zhody.',
        'course content and reading': 'Stručná osnova a Literatúra',
        'materials': 'Študijné Materiály'
    }
};