var arrLang = {
    'ENG': {
        'home': 'Home',
        'course content and reading': 'Course contents and Recomended Reading',
        'exercises': 'Exercises',
        'calculated examples': 'Calculated Examples',
        'lectures': 'Lectures',
        'language': 'Language',
        'conditions': 'Conditions for passing the course',
        'sylabus content': 'During the semester there will be credit tests (30%). To acomplish credit a student must obtain at least 15 of 30 points from credit tests, Additional 70 points can be obtained on the final exam. For final grade A at least 92, for B 83, C 74, D 65 and for E 56 points are needed. Students obtain knowledge of fundamentals of linear algebra, matrix algebra, analytic geometry in 3-dimensional space, polynomials and rational functions with real coefficients. They will be able to use elimination methods to solve systems of linear equations.',
        'week1': '1. Systems of linear equations. Gauss and Gauss-Jordan elimination method',
        'week2': '2. Matrices and determinants',
        'week3': '3. Arithmetic in space Rn. Linear (in)dependence, basis',
        'week4': '4. Matrix algebra, computatioéon of the inverse matrix',
        'week5': '5. Polynomials, roots, the Horner scheme',
        'week6': '6. Rational roots of polynomials with integer coefficients',
        'week7': '7. Irreducible polynomials, canonical factorizations of polynomials',
        'week8': '8. Ratioonal functions, elementary fractioons',
        'week9': '9. Vectors in R3, scalar and vector produts',
        'week10': '10. Equations of lines and planes',
        'week11': '11. Quadratic forms',
        'week12': '12. Quadric surfaces'
    },
    'SVK': {
        'home': 'Domov',
        'course content and reading': 'Stručná osnova a Literatúra',
        'exercises': 'Cvičenia',
        'calculated examples': 'Vyrátané Príklady',
        'lectures': 'Prednášky',
        'language': 'Jazyk',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'sylabus content': 'V priebehu semestra budú písomné previerky spolu 30 bodov, na získanie prístupu na skúšku treba získať spolu najmenej 15 bodov. Na skúške sa dá získať ešte 70 bodov. Na hodnotenia A je potrebné získať v súčte najmenej 92 bodov, na získanie hodnotenia B najmenej 83 bodov, na hodnotenie C najmenej 74 bodov, na hodnotenie D najmenej 65 bodov a na hodnotenie E najmenej 56 bodov. Študent získa základné vedomosti z lineárnej algebry, maticovej algebry, analytickej geometrie v 3-rozmernom priestore a o polynómoch a racionálnych funkciách s reálnymi koeficientami. Dokáže používať eliminačné metódy riešenia sústav lineárnych rovníc.',
        'week1': '1. Sústavy lineárnych rovníc. Gaussova a Gauss-Jordanova eliminačná metóda',
        'week2': '2. Matice a determinanty',
        'week3': '3. Aritmetika v priestore Rn. Lineárna (ne)závislosť, báza',
        'week4': '4. Maticová algebra, výpočet inverznej matice',
        'week5': '5. Polynómy, koreň, Hornerova schéma',
        'week6': '6. Racionálne korene polynómov s celočíéselnými koeficientami',
        'week7': '7. Rozklad na súčin ireducibilných polynómov',
        'week8': '8. Racionálne funkcie, elementárne zlomky',
        'week9': '9. Vektory v R3, skalárny a vektorový súčin',
        'week10': '10. Rovnice priamky a roviny',
        'week11': '11. Kvadratické formy',
        'week12': '12. Kvadratické plochy'
    }
};