var arrLang = {
    'ENG': {
        'home': 'Home',
        'course content and reading': 'Course contents and Recomended Reading',
        'exercises': 'Exercises',
        'calculated examples': 'Calculated Examples',
        'lectures': 'Lectures',
        'language': 'Language',
        'conditions': 'Conditions for passing the course',
        'sylabus content': 'Written tests during the semester for 30 points. For credit at least 50% of total is needed. Final exam at the end of semester for 70 points. Sum of all points determines the final evaluation. For evaluation A at least 92 points is needed,for evaluation B at least 83 points is needed, for evaluation C at least 74 points is needed, For evaluation D at least 65 points is needed,for evaluation E at least 56 points is needed. After completing this course, students should have developed an understanding of the fundamental concepts of single variable calculus and a range of skills allowing them to work effectively with the concepts of derivatives and integrals.',
        'week1': '1. Function of a real variable. Properties of functions, odd and even functions, boundedness, maximum, minimum, supremum, infimum, inverse function.',
        'week2': '2. Elementary functions, power function, exponential and logaritmic function, trigonometric and inverse trigonometric functions.',
        'week3': '3. Limit and continuity of a function. Finite and infinite limits. Limits at infinity.',
        'week4': '4. Continuity. Properties of continuous functions on a compact interval.',
        'week5': '5. Derivative. Definition of derivative and basic rules. Geometrical interpretation of derivative, differential.',
        'week6': "6. Monotonicity and local extrema. Lagrange's theorem",
        'week7': '7. Higher derivatives. Convexity of a function. Local extrema and 2-nd derivative. L‘Hospital rule.',
        'week8': '8. Sequence. Limit of a sequence. Arithmetic and geometric sequence. Recurrencies.',
        'week9': '9. Series. Convergence of infinite series. geometric series. Tests for convergence of positive series.',
        'week10': '10. Integration, basic ideas and definitions, elementary integrals, integration methods.',
        'week11': '11. Integration of rational functions, partial fractions.',
        'week12': '12. Definite integral, The fundamental theorem, integration methods and applications.',
        'point0': 'Students should demonstrate competency in the following skills:',
        'point1': '•Use rules of differentiation to differentiate functions.',
        'point2': '•Sketch the graph of a function using asymptotes, critical points, the derivative test for increasing/decreasing functions.',
        'point3': '•Apply differentiation to solve applied max/min problems.',
        'point4': '•Evaluate integrals by using the Fundamental Theorem of Calculus.',
        'point5': '•Evaluate integrals using techniques of integration, integration by parts, substitution, partial fractions.',
        'point6': '•Determine the convergence/divergence of an infinite series.'
    },
    'SVK': {
        'home': 'Domov',
        'course content and reading': 'Stručná osnova a Literatúra',
        'exercises': 'Cvičenia',
        'calculated examples': 'Vyrátané Príklady',
        'lectures': 'Prednášky',
        'language': 'Jazyk',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'sylabus content': 'V priebehu semestra budú písomné previerky spolu 30 bodov, na získanie prístupu na skúšku treba získať spolu najmenej 15 bodov. Na skúške sa dá získať ešte 70 bodov. Na hodnotenia A je potrebné získať v súčte najmenej 92 bodov, na získanie hodnotenia B najmenej 83 bodov, na hodnotenie C najmenej 74 bodov, na hodnotenie D najmenej 65 bodov a na hodnotenie E najmenej 56 bodov. Študent získa základné vedomosti z lineárnej algebry, maticovej algebry, analytickej geometrie v 3-rozmernom priestore a o polynómoch a racionálnych funkciách s reálnymi koeficientami. Dokáže používať eliminačné metódy riešenia sústav lineárnych rovníc.',
        'week1': '1. Pojem funkcie reálnej premennej. Vlastnosti funkcie, parita, ohraničenosť, maximum, minimum, supremum, infimum, inverzná funkcia.',
        'week2': '2. Elementárne reálne funkcie, mocninová, exponenciálna, logaritmická, Trigonometrické a cyklometrické funkcie.',
        'week3': '3. Limita a spojitosť funkcie. Konečné limity. Nevlastná limita. Limita v nevlastnom bode. Jednostranné limity.',
        'week4': '4. Spojitosť. Vlastnosti spojitých funkcií na uzavretom intervale.',
        'week5': '5. Pojem derivácie. Výpočet derivácie funkcie reálnej premennej. Geometrický význam derivácie, prvý diferenciál.',
        'week6': '6. Monotónnosť a lokálne extrémy. Vlastnosti diferencovateľnej funkcie na uzavretom intervale.',
        'week7': '7. Derivácie vyšších rádov. Konvexnosť a konkávnosť. Extrémy a 2.derivácia. L‘Hospitalovo pravidlo.',
        'week8': '8. Postupnosť ako funkcia na množine prirodzených čísel. Limita postupnosti. Vlastnosti. Postupnosť definovaná rekurentne.',
        'week9': '9. Nekonečné rady. Pojem konvergencie. Geometrický rad. Kritériá konvergencie radov s nezápornými členmi.',
        'week10': '10. Neurčitý integrál, definícia, elementárne integrály, metóda per partes a substitúcia.',
        'week11': '11. Integrovanie racionálnych funkcii, rozklad na elementárne zlomky.',
        'week12': '12. Určitý integrál (Riemannov), vzťah medzi integrálom a primitívnou funkciou, metódy integrovania, aplikácie určitého integrálu.',
        'point0': 'Je schopný:',
        'point1': '•Derivovať elementárne funkcie.',
        'point2': '•Načrtnúť graf funkcie s vyznačením lokálnych extrémov, intervalov rastu a klesania, asymptot.',
        'point3': '•Aplikovať diferenciálny počet na riešenie extremálnych úloh.',
        'point4': '•Integrovať použitím základnej vety integrálneho počtu.',
        'point5': '•Integrovať použitím integračných metód per partes a substitúcie.',
        'point6': '•Rozhodnúť o konvergencii číselného radu.'
    }
};