var arrLang = {
    'ENG': {
        'home': 'Home',
        'language': 'Language',
        'conditions': 'Conditions for passing the course',
        'point0': 'Assesment: Succesful commitment of semestral tasks (max. 40 points), obtaining at least 20 from 40 possible points',
        'point1': 'Examination: Awarded assesment, accomplishing of written examination (max. 60 points)',
        'point2': 'Introduction to HMI.',
        'point3': 'Natural communication, types of human-machine interfaces.',
        'point4': 'Human perception and recognition.',
        'point5': 'Psychology of users, attention, thinking, perception of visual, sound and haptic incitements.',
        'point6': 'Design rules for good user interface.',
        'point7': 'Sound interaction.',
        'point8': 'Basics of acoustics.',
        'point9': 'Psychoacoustics.',
        'point10': 'Input/output sound sensors: microphones loudspeakers, etc.',
        'point11': 'Sound interface applications: recognition, syntheses, identification, etc..',
        'point12': 'Visual interface, properties of light.',
        'point13': 'Perception of light by humans.',
        'point14': 'Applications for visual modality: recognition, identification of faces, objects, etc.',
        'point15': 'Input output sensors for visual interface: cameras, displays, etc.',
        'point16': 'Other modalities: smell, touch, taste.',
        'point17': 'Technologies, applications, sensors.',
        'point18': 'Brain-coputer interface: applications, concepts, sensors.',
        'point19': 'Concept of combined reality, virtual reality, technologies, existing scientific and commercial projects.',
        'course content and reading': 'Course contents and Recomended Reading',
        'materials': 'Study Materials'
    },
    'SVK': {
        'home': 'Domov',
        'language': 'Jazyk',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'point0': 'Zápočet: Úspešné odovzdanie zadaní (za 40 bodov), získanie minimálne 20 zo 40 bodov',
        'point1': 'Skúška: Udelený zápočet, vykonanie skúšky písomnou formou (za 60 bodov)',
        'point2': 'Úvod do HMI.',
        'point2': 'Prirodzená komunikácia, multimodalita, typy rozhraní človek - stroj.',
        'point2': 'Zásady správneho návrhu rozhraní (GUI).',
        'point2': 'Ľudské vnímanie a rozpoznávanie.',
        'point2': 'Psychológia používateľov, pozornosť, myslenie, vnímanie podnetov.',
        'point2': 'Zvuková interakcia.',
        'point2': 'Vlastnosti zvuku a reči.',
        'point2': 'Vnimanie zvuku -psychoakustika.',
        'point2': 'Aplikácie pre zvukové rozhrania:Syntéza reči,Rozpoznávanie reči, Identifikácia.',
        'point2': 'Senzory na zber a reprodukciu zvuku.',
        'point2': 'Vizuálna interakcia.',
        'point2': 'Vlastnosti svetla- obrazu.',
        'point2': 'Vnímanie statického a dynamického obrazu.',
        'point2': 'Aplikácie pre vizuálne rozhrania: Rozpoznávanie tváre- objektov,gest, identifikácia, atď.',
        'point2': 'Senzory na zber a zobrazenie obrazu/ pohybu Rozhrania pre zvyšné vnemy: hmat, čuch, chuť.',
        'point2': 'Technológie, koncepty a použitie.',
        'point2': 'Rozhranie mozog – stroj.',
        'point2': 'Senzory, spôsoby činnosti,využitie.',
        'point2': 'Koncept zmiešanej reality, virtuálna realita, technológie, existujúce výskumné a komerčné projekty.',
        'course content and reading': 'Stručná osnova a Literatúra',
        'materials': 'Študijné Materiály'
    }
};