var arrLang = {
    'ENG': {
        'home': 'Home',
        'language': 'Language',
        'conditions': 'Conditions for passing the course',
        'result': 'Learning outcomes of the course unit',
        'course content and reading': 'Course contents and Recomended Reading',
        'point0': 'There are 2 written tests during the semester, 20 points per each.',
        'point1': 'It is necessary to obtain at least 20 points from these tests (to get the opportunity to write the exam).',
        'point2': 'Then 60 points can be obtained at the written exam.',
        'point3': 'The credits are not assigned to a student, that obtained less than 56 points.',
        'point4': 'The students get konwledge on basic algorithms in computer science, graph theory, number theory, and cryptology. The students get practical experiences in analysis of algorithms and determination of their computational complexity. The students are able to analyse algorithms, determine their computational/memory complexities and can compare the complexity of algorithms.',
        'point5': '1. Algorithm. Computational complexity. Comparing the growth of functions.',
        'point6': '2. Sums.',
        'point7': '3. Recurrences.',
        'point8': '4. Sorting.',
        'point9': '5. Independent sets and graph colouring.',
        'point10': '6. Maximum flow I.',
        'point11': '7. Matrix operations.',
        'point12': '8. Number-theoretic algorithms.',
        'point13': '9. String matching I.',
        'point14': '10. String matching II.',
        'point15': '11. Complexity classes I.',
        'point16': '12. Complexity classes II.',
        'materials': 'Study Materials'
    },
    'SVK': {
        'home': 'Domov',
        'language': 'Jazyk',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'result': 'Výsledky vzdelávania',
        'course content and reading': 'Stručná osnova a Literatúra',
        'point0': 'V priebehu semestra budú 2 písomné testy, každý za 20 bodov.',
        'point1': 'Na získanie zápočtu je potrebné získať aspoň 20 bodov.',
        'point2': 'Za písomnú skúšku možno získať 60 bodov.',        
        'point3': 'Kredity sa neudelia študentovi, ktorý nezískal zápočet alebo získal menej ako 56 bodov.',
        'point4': 'Študenti získajú znalosti o základných algoritmoch z informatiky, teórie grafov, teórie čísel, kryptológie. Študenti získajú praktické skúsenosti z analýzy algoritmov a určenia ich výpočtovej zložitosti. Študenti dokážu analyzovať algoritmus, nájsť vzťah pre jeho výpočtovú/pamäťovú zložitosť a dokážu porovnať zložitosť algoritmov.',
        'point5': '1. Algoritmus. Výpočtová zložitosť. Porovnávanie rastu funkcií.',
        'point6': '2. Rady.',
        'point7': '3. Rekurencie.',
        'point8': '4. Triedenie.',
        'point9': '5. Nezávislé množiny a farbenie grafov.',
        'point10': '6. Toky v sieťach I.',
        'point11': '7. Maticové operácie.',
        'point12': '8. Vybrané algoritmy z teórie čísel.',
        'point13': '9. Vyhľadávanie reťazcov v textoch I.',
        'point14': '10. Vyhľadávanie reťazcov v textoch II.',
        'point15': '11. Triedy zložitosti I.',
        'point16': '12. Triedy zložitosti II.',
        'materials': 'Študijné Materiály'
    }
};