var arrLang = {
    'ENG': {
        'home': 'Home',
        'language': 'Language',
        'conditions': 'Conditions for passing the course',
        'result': 'Learning outcomes of the course unit',
        'course content and reading': 'Course contents and Recomended Reading',
        'point0': 'There will be two written exams worth 20 points each, one assignment from discrete programming and a final 24h assignment worth 40 points. Student with less than 20 points after the two written exams will not be given the credit.',
        'point1': "The goal is to gain knowledge in the basic theoretical and practical approaches in classical ciphers, to know the historical background of their development and use in real-life; and to be informed with the lives of the important historic figures that helped to develop the classical ciphers. The subject also broadens students' experience in discrete programming techniques.",
        'point2': '1. Basic terminology',        
        'point3': '2. The evolution of cryptographic algorithms',
        'point4': '3. Ciphers and permutations',
        'point5': '4. The basics of modular arithmetics',
        'point6': '5. Statistical properties of language',
        'point7': '6. Anagrams and transposition ciphers',
        'point8': '7. Substitution algorithms',
        'point9': '8. Computers and classical ciphers',
        'point10': '9. Substitution-transposition ciphers',
        'point11': '10. Ciphers with very long key',
        'point12': '11. Rotor ciphers',
        'point13': '12. The cracking of ENIGMA',
        'materials': 'Study Materials'
    },
    'SVK': {
        'home': 'Domov',
        'language': 'Jazyk',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'result': 'Výsledky vzdelávania',
        'course content and reading': 'Stručná osnova a Literatúra',
        'point0': 'V semestra budú dve zápočtovky po 20 bodov, jedna úloha z diskrétneho programovania a záverečné 24hod zadanie za 40 bodov. Kredity sa neudelia študentovi, ktorý z 2 písomných previerok získa menej ako 20 bodov.',
        'point1': 'Predmet má za úlohu oboznámiť záujemcov so základnými teoretickými a praktickými postupmi v tzv. klasických šifrách, spoznať historické súvislosti ich vývoja a nasadenia a životné osudy významných osobností, ktoré prispeli ku ich rozvoju. Zároveň predmet rozvíja schopnosti poslucháčov v tzv. diskrétnych programovacích technikách.',
        'point2': '1. Základné pojmy o šifrovaní',        
        'point3': '2. Evolúcia kryptografických algoritmov',
        'point4': '3. Šifrovanie a permutácie',
        'point5': '4. Základy modulárnej aritmetiky',
        'point6': '5. Štatistické vlastnosti jazyka',
        'point7': '6. Anagramy a transpozičné šifry',
        'point8': '7. Prehľad substitučných algoritmov',
        'point9': '8. Počítače a klasické šifry',
        'point10': '9. Substitučno – transpozičné šifry',
        'point11': '10. Šifry s veľmi dlhým kľúčom',
        'point12': '11. Rotorové šifry',
        'point13': '12. Lúštenie ENIGMY',
        'materials': 'Študijné Materiály'
    }
};