var arrLang = {
    'ENG': {
        'home': 'Home',
        'language': 'Language',
        'conditions': 'Conditions for passing the course',
        'result': 'Learning outcomes of the course unit',
        'course content and reading': 'Course contents and Recomended Reading',
        'point0': 'Grades are allocated according to current FEI rating scale based on student test score.',
        'point1': 'Acquire a good knowledge of the construction of modern operating systems. To become familiar with the structures and algorithms used by the OS kernel. Learn how to apply theoretical knowledge in practice.',
        'point2': '1. Introduction to Operating Systems',        
        'point3': '2. System calls',
        'point4': '3. Processes and threads',
        'point5': '4. Process scheduling',
        'point6': '5. Process synchronization',
        'point7': '6. Deadlocks and livelocks',
        'point8': '7. Memory Management',
        'point9': '8. Memory Allocation',
        'point10': '9. Filesystem',
        'point11': '10. Implementation of file systems',
        'point12': '11. RAID and peripherals',
        'point13': '12. Security of operating systems',
        'materials': 'Study Materials'
    },
    'SVK': {
        'home': 'Domov',
        'language': 'Jazyk',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'result': 'Výsledky vzdelávania',
        'course content and reading': 'Stručná osnova a Literatúra',
        'point0': 'Známky sú prideľované podľa platnej klasifikačnej stupnice FEI na základe študentom vykonanej skúšky.',
        'point1': 'Získať základné vedomosti z oblasti stavby jadra moderných operačných systémov. Oboznámiť sa s používanými algoritmami a štruktúrami jadra OS. Naučiť sa aplikovať teoretické vedomosti v praxi.',
        'point2': '1. Úvod do operačných systémov',        
        'point3': '2. Systémové volania',
        'point4': '3. Procesy a vlákna',
        'point5': '4. Plánovanie procesov',
        'point6': '5. Synchronizácia procesov',
        'point7': '6. Uviaznutie procesov',
        'point8': '7. Správa pamäti',
        'point9': '8. Prideľovanie pamäti',
        'point10': '9. Súborový systém',
        'point11': '10. Implementácia súborového systému',
        'point12': '11. RAID, periférne zariadenia',
        'point13': '12. Ochrana a bezpečnosť operačných systémov',
        'materials': 'Študijné Materiály'
    }
};