var arrLang = {
    'ENG': {
        'home': 'Home',
        'language': 'Language',
        'conditions': 'Conditions for passing the course',
        'result': 'Learning outcomes of the course unit',
        'course content and reading': 'Course contents and Recomended Reading',
        'point0': 'The midterm exam is worth 20% and lab assignments are worth 40%.',
        'point1': 'Submission of the project and at least 50% success rate on the midterm exam is required before being allowed to take the final exam. The final exam is worth 40%.',
        'point2': 'Introductory software engineering course focuses on practical processes and procedures used in developing large and complex software systems. The course covers all stages of software life-cycle – requirements specification and analysis, design, partially also implementation, and testing.',        
        'point3': 'Also covered will be many different aspects of software development, such as project management, change management, software reuse, rapid development, and secure software development. Unified Modeling Language is presented and used throughout the course.',
        'point4': '1. Systems and software engineering',
        'point5': '2. Critical systems',
        'point6': '3. Software processes',
        'point7': '4. Project & change management',
        'point8': '5. Requirements engineering',
        'point9': '6. System modeling',
        'point10': '7. Architectural design',
        'point11': '8. Object-oriented design',
        'point12': '9. Rapid software development & extreme programming',
        'point13': '10. Software reuse',
        'point14': '11. Software testing',
        'point15': '12. Security engineering',
        'materials': 'Study Materials'
    },
    'SVK': {
        'home': 'Domov',
        'language': 'Jazyk',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'result': 'Výsledky vzdelávania',
        'course content and reading': 'Stručná osnova a Literatúra',
        'point0': 'V priebehu semestra bude jeden písomný test s váhou 20% celkového hodnotenia. Semestrálny projekt počas semestra je s váhou 40% z celkového hodnotenia.',
        'point1': 'Podmienkou prístupu na skúšku je odovzdanie semestrálnej práce a aspoň 50% úspešnosť na priebežnom písomnom teste. Záverečný test je rozsahu 40% celkového hodnotenia. Známky sú pridelené podľa platnej klasifikačnej stupnice FEI.',
        'point2': 'Základy softvérového inžinierstva so zameraním na praktické postupy, ktoré sa používajú pri vývoji veľkých a zložitých softvérových systémov. Výučba pokryje všetky etapy životného cyklu softvéru – analýzu a špecifikáciu požiadaviek, návrh, čiastočne implementáciu a testovanie.',        
        'point3': 'Zameranie bude aj na ďalšie aspekty vývoja softvéru, najmä na projektový manažment, manažment zmien, znovupoužitie softvéru, rapídny vývoj a bezpečnosť v softvérovom inžinierstve. Súčasťou výučby bude aj oboznámenie sa s jazykom na modelovanie UML.',
        'point4': '1. Systemové a softvérové inžinierstvo',
        'point5': '2. Kritické systémy',
        'point6': '3. Softvérový proces',
        'point7': '4. Projektový manažment a manažment zmien',
        'point8': '5. Špecifikácia softvéru',
        'point9': '6. Modelovanie systémov',
        'point10': '7. Návrh architektúry',
        'point11': '8. Objektovo orientovaný návrh',
        'point12': '9. Rapídne a extrémne programovanie',
        'point13': '10. Recyklácia a opätovné použitie softvéru',
        'point14': '11. Testovanie softvéru',
        'point15': '12. Bežpečnosť v softvérovom inžinerstve',
        'materials': 'Študijné Materiály'
    }
};
