var arrLang = {
    'ENG': {
        'home': 'Home',
        'language': 'Language',
        'conditions': 'Conditions for passing the course',
        'result': 'Learning outcomes of the course unit',
        'course content and reading': 'Course contents and Recomended Reading',
        'point0': 'Active participations in seminars. During the term student can achieve 50 points and another 50 points can achieve for the exam.',
        'point1': 'Points during the term: completing seminar assignments and tests (written quiz and programming). Final exam: written test and defence of the final assignment.',  
        'point2': 'To be able to prepare supporting materials for web page design, to be familiar with web design standards, to know how to choose suitable software for design of web applications, to be able to create a dynamical and interactive web page using programming technologies on the client side, to know to evaluate quality and impact of the created web page',      
        'point3': 'Overview and comparison of technologies and methodologies for the web application design.',
        'point4': 'Web application structure (client-server application).',
        'point5': 'Basic characteristics and comparison of leading web browsers.',
        'point6': 'Standars for development of web applications.',
        'point7': 'Tools for web application development.',
        'point8': 'Technologies for development of client side applications.',
        'point9': 'Overview of suitable formats for web multimedial content.',
        'point10': 'Structure of web pages - Hypertext language HTML.',
        'point11': 'Hierarchical document object model (DOM).',
        'point12': 'Graphical web page design - Cascade styles.',
        'point13': 'Adaptation of web pages to various user’s end devices.',
        'point14': 'Client programming using JavaScript.',
        'point15': 'AJAX.',
        'point16': 'JS libraries – tools for effective design of web pages (jQuery).',
        'point17': 'Introduction to XML.',
        'point18': 'Security, accessibility and attractivity of web applications.',
        'materials': 'Study Materials'
    },
    'SVK': {
        'home': 'Domov',
        'language': 'Jazyk',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'result': 'Výsledky vzdelávania',
        'course content and reading': 'Stručná osnova a Literatúra',
        'point0': 'Aktívna účasť na cvičeniach. V priebehu semestra môže študent získať 50 bodov a na skúške 50 bodov.',
        'point1': 'Získanie bodov počas semestra: odovzdanie semestrálnych zadaní, test, písomka spočívajúca v naprogramovaní stanovených úloh. Záverečné hodnotenie: písomná skúška + odovzdanie a obhajoba skúškového zadania.',
        'point2': 'Vedieť naformulovať a pripraviť podklady pre tvorbu WWW stránok, orientovať sa v štandardoch tvorby WWW stránky, vybrať si vhodný softvér na tvorbu web aplikácií, vytvoriť dynamickú a interaktívnu web stránku za pomoci programovacích techník na strane klienta, ohodnotiť kvalitu a dosah vytvorenej stránky.',        
        'point3': 'Prehľad a porovnanie technológií a metodológií pre vývoj web aplikácií.',
        'point4': 'Štruktúra Web aplikácií (architektúra klient-server).',
        'point5': 'Základná charakteristika a porovnanie vedúcich web prehliadačov.',
        'point6': 'Štandardy pre vývoj web aplikácií.',
        'point7': 'Nástroje na vývoj web aplikácií.',
        'point8': 'Technológie na vývoj aplikácií na strane klienta.',
        'point9': 'Prehľad vhodných formátov multimédií pre web.',
        'point10': 'Definovanie štruktúry webových stránok - hypertextový jazyk HTML.',
        'point11': 'Hierarchický objektový model dokumentu (DOM).',
        'point12': 'Návrh grafického dizajnu web stránok - kaskádové štýly.',
        'point13': 'Zohľadnenie rôznych koncových zariadení a médií.',
        'point14': 'Programovanie na strane klienta pomocou JavaScriptu',
        'point15': 'AJAX.',
        'point16': 'JS knižnice – nástroj pre efektívny návrh web stránok (jQuery).',
        'point17': 'Úvod do XML.',
        'point18': 'Bezpečnosť, dostupnosť a atraktivita web aplikácií.',
        'materials': 'Študijné Materiály'
    }
};
