var arrLang = {
    'ENG': {
        'home': 'Home',
        'language': 'Language',
        'conditions': 'Conditions for passing the course',
        'point0': '• Credit eligibility = exam admission: 100% participation at the seminars and completion of all seminar projects. The projects will be evaluated by <0-20> points.',
        'point1': '• Reaching at least 60% at the exam test (i.e. at least 48 points out of 80)',
        'point2': 'Understanding of environmental aspects of technology and review of fundamental environmental concepts.',
        'point3': 'Reading of expert literature with understanding.',
        'point4': 'Application of basic physics in environmental sciences. ',
        'point5': 'Acquiring knowledge and overview about basic components of environment (e.g. water, air, energy), monitoring methods and pollution management.',
        'point6': '1. Basic concepts and definitions used in environmental sciences.',
        'point7': '2. Mass and energy, transport processes.',
        'point8': '3. Basic components of environment: water I.',
        'point9': '4. Basic components of environment: water II.',
        'point10': '5. Basic components of environment: air I.',
        'point11': '6. Basic components of environment: air II.',
        'point12': '7. Emissons and emission management.',
        'point13': '8. Greenhouse effect.',
        'point14': '9. Ozone.',
        'point15': '10. Monitoring methods in environmental engineering.',
        'point16': '11. Physical factors in environmet I.',
        'point17': '12. Physical factors in environment II.',
        'course content and reading': 'Course contents and Recomended Reading',
        'exam': 'Exams'
    },
    'SVK': {
        'home': 'Domov',
        'language': 'Jazyk',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'point0': '• Získanie zápočtu = pripustenie ku skúške: 100% účasť na cvičeniach a odovzdanie zadaní z výpočtových cvičení. Kvalita a úroveň vypracovania zadaní sa ohodnotí pridelením 0-20 bodov.',
        'point1': '• Vypracovanie skúškového testu na viac ako 60% (t.j. získanie viac ako 48 bodov z 80)',
        'point2': 'Pochopenie vzťahu medzi technikou a prírodným prostredím a získanie prehľadu o základných pojmoch používaných v environmentalistike.',
        'point3': 'Čítanie odborných textov z environmentalistiky s porozumením.',
        'point4': 'Aplikácie základných poznatkov z fyziky v problematike životného prostredia.',
        'point5': 'Študent získa vedomosti o základných zložkách životného prostredia (voda, vzduch, energia), metódach ich monitorovania a manažmente ich znečistenia.',
        'point6': '1. Základné ekologické pojmy a definície.',
        'point7': '2. Prenos hmoty a energie.',
        'point8': '3. Základné zložky životného prostredia: voda I.',
        'point9': '4. Základné zložky životného prostredia: voda II.',
        'point10': '5. Základné zložky životného prostredia: vzduch I.',
        'point11': '6. Základné zložky životného prostredia: vzduch II.',
        'point12': '7. Emisie a manažment emisií.',
        'point13': '8. Skleníkový efekt.',
        'point14': '9. Ozón.',
        'point15': '10. Metódy monitorovania životného prostredia.',
        'point16': '11. Vplyvy vybraných fyzikálnych faktorov na životné prostredie I.',
        'point17': '12. Vplyvy vybraných fyzikálnych faktorov na životné prostredie II.',
        'course content and reading': 'Stručná osnova a Literatúra',
        'exam': 'Skúšky'
    }
};