var arrLang = {
    'ENG': {
        'home': 'Home',
        'language': 'Language',
        'course content and reading': 'Course contents and Recomended Reading',
        'exercises': 'Exercises',
        'programs': 'Software',
        'lectures': 'Lectures',
        'conditions': 'Conditions for passing the course',
        'point1': 'credit, examination',
        'point2': 'Total mark in the examination students will be derived from scoring as follows:',
        'point3': 'a) exercises max. 60 points',
        'point4': 'b) the written test max. 40 points.',
        'point5': 'To pass the test a student must achieve a total of (a + b) at least 56 points (maximum 100 points), while the percentage in the examination is conditional upon a minimum of 30 points for exercise and 20 points on the written exam.',
        'point6': 'Student will obtain the basic knowledge and experience in designing algorithms in multiple programming paradigms. Student will learn the basics of Python programming language.',
        'point7': '1. Introduction to Python and programming.',
        'point8': '2. Basic algorithmic constructions.',
        'point9': '3. Arithmetic.',
        'point10': '4. Complex loops.',
        'point11': '5. Functions.',
        'point12': '6. Variables, call by value/call by reference.',
        'point13': '7. Complex data types, strings.',
        'point14': '8. Searching and sorting.',
        'point15': '9. Recursion.',
        'point16': '10. Using files.',
        'point17': '11. Graphical user interface.'
    },
    'SVK': {
        'home': 'Domov',
        'language': 'Jazyk',
        'course content and reading': 'Stručná osnova a Literatúra',
        'exercises': 'Cvičenia',
        'programs': 'Programy',
        'lectures': 'Prednášky',
        'conditions': 'Podmienky na absolvovanie predmetu',
        'point1': 'zápočet, skúška',
        'point2': 'Celková známka študentov na skúške bude odvodená od bodového hodnotenia nasledovne:',
        'point3': 'a) cvičenia max. 60 bodov,',
        'point4': 'b) písomná časť skúšky max. 40 bodov.',
        'point5': 'Pre úspešné absolvovanie skúšky musí študent dosiahnuť celkovo (a+b) minimálne 56 bodov (maximum je 100 bodov), pričom úspešnosť na skúške je podmienená dosiahnutím minimálne 30 bodov za cvičenia a 20 bodov z písomnej časti skúšky.',
        'point6': 'Študent získa základné vedomosti a zručnosti pri návrhu algoritmov a multiparadigmovom programovaní. Študent zvládne základy jazyka Python.',
        'point7': '1. Úvod do jazyka Python a tvorby algoritmov.',
        'point8': '2. Základné algoritmické konštrukcie.',
        'point9': '3. Počítanie s číslami.',
        'point10': '4. Vnorené cykly.',
        'point11': '5. Funkcie.',
        'point12': '6. Premenné, volanie hodnotou a odkazom.',
        'point13': '7. Zložené dátové typy, reťazce.',
        'point14': '8. Vyhľadávanie a triedenie.',
        'point15': '9. Rekurzia.',
        'point16': '10. Práca so súborom.',
        'point17': '11. Práca s grafickým rozhraním.'
    }
};